FROM public.ecr.aws/lambda/python:3.9

# Install system dependencies
RUN yum update -y && yum install -y gcc

# Install Python dependencies
RUN pip install --no-cache-dir \
    numpy==1.26 \
    matplotlib==3.7.1 \
    scapy \
    pyyaml \
    boto3 \
    dpkt

# Copy application files
COPY extract_payload.py plot_random_csv.py drx.py s3_extract_payload.py s3_plot_csv.py lambda_handler.py ./
COPY difi_utils/ ./difi_utils/

# Set the CMD to your handler
CMD ["lambda_handler.handler"]